base-url: "${BASE_URL:http://localhost:8080}"
spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  session:
    dynamodb:
      table-name: ${DYNAMO_SESSION_TABLE:sessions}
      max-inactive-interval: 1h
      region: eu-west-2
      endpoint: ${DYNAMO_ENDPOINT:}
      create-table: ${DYNAMO_SESSION_CREATE_TABLE:true}
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  freemarker:
    template-loader-path: "classpath:/templates"
    suffix: .ftl
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  security:
    oauth2:
      client:
        registration:
          login:
            client-id: "${COGNITO_CLIENT_ID:dummy}"
            client-secret: "${COGNITO_CLIENT_SECRET:}"
            scope: openid, email, profile
            authorization-grant-type: authorization_code
            client-name: website
            region: ${AWS_REGION:eu-west-2}
            user-pool-id: ${COGNITO_USER_POOL_ID:eu-west-2_fl4u3kveF}
            session-salt: "${COGNITO_SESSION_SALT:}"
          website:
            client-id: "${WEBSITE_CLIENT_CREDENTIALS_ID:dummy}"
            client-secret: "${WEBSITE_CLIENT_CREDENTIALS_SECRET:}"
            scope: "${WEBSITE_CLIENT_TRUSTED_SCOPE:graphql/trusted-client}"
            authorization-grant-type: client_credentials
            client-name: website-client
        provider:
          login:
            issuer-uri: ${COGNITO_ISSUER_URI:}
            user-name-attribute: email
          website:
            issuer-uri: ${COGNITO_ISSUER_URI:}

debug: false
server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    session:
      timeout: 24h

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

club:
  club-name: ${CLUBNAME:My Cricket Club}
  logo: "/mcc/img/logos/mcc-logo-header.svg"
  favicon: "/mcc/img/logos/mcc-logo-favicon.svg"
  club-address: ${CLUB_ADDRESS:}
  phone-number: "${CLUB_PHONE_NUMBER:(01234) 567890}"
  google-analytics-key: "${GOOGLE_ANALYTICS_KEY:}"
  google-maps-api-key: ${GOOGLE_MAPS_API_KEY:}
  play-cricket:
    enabled: true
    site: merstham
  fundraising:
    justgiving: ${JUSTGIVING_LINK:}
    easyfundraising: ${EASYFUNDRAISING_LINK:}
  social:
    twitter:
      handle: ${TWITTER_HANDLE:}
    facebook:
      handle: ${FACEBOOK_HANDLE:}
  cookies:
    api-key: ${COOKIE_CONTROL_KEY:}
    product-code: ${COOKIE_CONTROL_PRODUCT:PRO}
    optional-cookie-categories:
      - name: social
        label: Social Media
        enabled: true
        description: Blah
        cookieNames:
          - "_utma"
          - "gid"
graph:
  graph-uri: ${GRAPH_URI:http://localhost:8090/graphql}

resources:
  base-url: "${RESOURCES_BASE_URL}"
  base-directory: "${RESOURCES_BASE_DIRECTORY:../infrastructure/spaces-data}"
  bucket: "${RESOURCES_BUCKET_NAME:resources}"
  region: "${RESOURCES_BUCKET_REGION:eu-west-2}"
  api-endpoint: ${RESOURCES_BASE_URL:}

payments:
  pay-later:
    enabled: false
    disabled-reason: ~
  paypal:
    enabled: true
    disabled-reason: ~
    client-id: ${PAYPAL_CLIENT_ID:}
    client-secret: ${PAYPAL_CLIENT_SECRET:}
    sandbox: true
  stripe:
    enabled: true
    disabled-reason: ~
    api-key: ${STRIPE_API_KEY:}
    publishable-key: ${STRIPE_PUBLISHABLE_KEY:}
  gocardless:
    enabled: true
    disabled-reason: ~
    access-token: ${GOCARDLESS_ACCESS_TOKEN:}
    sandbox: true
    mandate-description: Membership and Match Fees
  bank:
    enabled: true
    disabled-reason: ~
    account-name: ${BANK_ACCOUNT_NAME:Merstham Cricket Club}
    account-number: ${BANK_ACCOUNT_NUMBER:49244507}
    sort-code: ${BANK_ACCOUNT_SORT_CODE:56-00-46}

facebook:
  application-id: ${FACEBOOK_APP_ID}
  application-secret: ${FACEBOOK_APP_SECRET}
  page-id: ${FACEBOOK_PAGE_ID}
  access-token: ${FACEBOOK_PAGE_ACCESS_TOKEN}

twitter:
  api-key: ${TWITTER_API_KEY}
  api-secret: ${TWITTER_API_SECRET}
  oauth-access-token: ${TWITTER_OAUTH_ACCESS_TOKEN}
  oauth-access-token-secret: ${TWITTER_OAUTH_ACCESS_TOKEN_SECRET}

contact-methods:
  email:
    enabled: true
  phone:
    enabled: true
    default-region: GB
