server:
  port: 8090

spring:
#  mvc:
#    log-request-details: true

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:localhost}:5432/${DATABASE_NAME:}"
    username: ${DATABASE_USER:}
    password: ${DATABASE_PASSWORD:}
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
  cache:
    dynamodb:
      table-name: GraphQLCache
      time-to-live: 300s
      region: eu-west-2
      endpoint: ${DYNAMO_ENDPOINT:}
      create-table: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI:}

management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

debug: false

configuration:
  database-secret: ${DATABASE_SECRET:}
  play-cricket:
    api-token: ${PLAY_CRICKET_API_TOKEN:}
    site-id: ${PLAY_CRICKET_SITE_ID:}
    team-refresh-cron: "0 0 */2 * * ?"
    fixture-refresh-cron: "0 */10 * * * ?"
    scheduler-zone: "Europe/London"
