server:
  port: 8090

spring:
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  datasource:
    url: "jdbc:postgresql://localhost:5432/${DATABASE_NAME:}"
    username: ${DATABASE_USER:}
    password: ${DATABASE_PASSWORD:}
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  cache:
    redis:
      time-to-live: 300s
      key-prefix: "graph-cache:"
      use-key-prefix: true
      enable-statistics: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_fl4u3kveF


debug: true

configuration:
  database-secret: ${DATABASE_SECRET:}
