spring:
  freemarker:
    template-loader-path: "classpath:/templates"
    suffix: .ftl
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

keycloak:
  auth-server-url: ${KEYCLOAK_URL:https://login.new.mersthamcc.co.uk/auth}
  realm: ${KEYCLOAK_REALM:new.mersthamcc.co.uk}
  resource: ${KEYCLOAK_CLIENT_ID:dummy}
  ssl-required: external
  credentials:
    secret: "${KEYCLOAK_CLIENT_SECRET:dummy}" #pragma: allowlist secret
  use-resource-role-mappings: false
  principal-attribute: preferred_username

debug: false
server:
  port: 8080
  forward-headers-strategy: framework

club:
  club-name: ${CLUBNAME:Merstham Cricket Club}
  logo: "/assets/mcc/img/header_logo.png"
  phone-number: "(01737) 645485"
  google-analytics-key: "UA-48714932-4"
  play-cricket:
    enabled: false
    site: merstham
  social:
    twitter:
      handle: ${TWITTER_HANDLE:mersthammagics}
    facebook:
      handle: ${FACEBOOK_HANDLE:MersthamCC}
  cookies:
    api-key: ${COOKIE_CONTROL_KEY:}
    product-code: ${COOKIE_CONTROL_PRODUCT:PRO}
    optional-cookie-categories:
      - name: social
        label: Social Media
        enabled: true
        description: Blah
        cookieNames:
          - "_utma"
          - "gid"
graph:
  graph-uri: ${GRAPH_URI}

payments:
  pay-later:
    enabled: true
    disabled-reason: ~
