version: 2.1

jobs:
  build-keycloak-extension:
    docker:
      - image: 'cimg/openjdk:11.0'
    steps:
      - checkout
      - run:
          name: Build
          working_directory: keycloak/keycloak-sms2fa
          command: |
            gradle build

workflows:
  main:
    jobs:
      - build-keycloak-extension:
          context: SonarCloud

