ckfinder:
  connector:
    licenseName: '%env(CKFINDER_LICENCE_NAME)%'
    licenseKey: '%env(CKFINDER_LICENCE_KEY)%'
    authenticationClass: App\Auth\CKFinderAuth
    resourceTypes: ~
    backends: ~
