club:
  name: Merstham Cricket Club
  logo: "/assets/mcc/img/header_logo.png"
  phone: "(01737) 645485"
  playcricket:
    enabled: true
    subsitePrefix: merstham
  social:
    twitter:
      handle: mersthammagics

    facebook:
      handle: MersthamCC

  cookies:
    apiKey: "f462c1a63422c4ca6ab426c399bf6ecead720cc2"
    product: "PRO"

    optionalCookiesCategories:
      - name: social
        label: Social Media
        enabled: true
        description: Blah
        cookieNames:
          - "_utma"
          - "gid"

  analytics:
    googleAnalyticsKey: "UA-48714932-4"
