apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Graphite
    orgId: 1
  - name: mcc_logs
    orgId: 1
  - name: mcc_data
    orgId: 1
  - name: prometheus
    orgId: 1

datasources:
  - name: mcc_logs
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    isDefault: false
    version: 1
    editable: false
  - name: mcc_data
    type: postgres
    access: proxy
    orgId: 1
    url: ${MCC_CONTENT_SERVER}:5432
    database: ${MCC_CONTENT_DATABASE}
    withCredentials: false
    user: ${MCC_CONTENT_USER}
    isDefault: false
    jsonData:
      sslmode: disable
      postgresVersion: 1000
    secureJsonData:
      password: ${MCC_CONTENT_PASSWORD}
    version: 1
    editable: false
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
