name: On Merge
on:
  push:
    branches:
      - main

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version-file: '.java-version'

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-on-merge
          restore-keys: ${{ runner.os }}-sonar-on-merge

      - name: Prepare
        shell: bash
        run: |
          echo "Removing symbolic link to assets..."
          rm frontend/src/main/resources/static

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew build sonarqube --info
