name: PR Checker
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Prepare
        shell: bash
        run: |
          echo "Removing symbolic link to assets..."
          rm src/main/resources/static

      - name: Run Tests
        run: ./gradlew build
